.TH "sunrise\-siren\-studio" 1 "28 May 2025" "v1.3.0" "Sunrise Siren Studio"
.SH "NAME"
Sunrise Siren Studio \- Control program for Sunrise Siren 3000

.SH "SYNOPSIS"
sunrise-siren-studio

.SH "REQUIREMENTS"
The most important requirement to use Sunrise Siren Studio, is a Sunrise Siren 3000: the most epic NeoPixel based alarm clock!

.SH "AUTHOR"
Sunrise Siren Studio and the ESP32 firmware are proudly made by ngkon.

.SH "BUGS"
Bugs in both Sunrise Siren Studio and the ESP32 firmware can be reported on the dedicated GitHub page:
.PP 
https://github.com/ILoveAndLikePizza/SunriseSiren3000/issues

.SH "LICENSE"
The Sunrise Siren 3000 project is licensed under the GNU General Public License v3.